// Form App - JavaScript
// =========================================

// DOM Elements
const form = document.getElementById('businessForm');

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    console.log('Form App initialized');
});

// Form Submission
form.addEventListener('submit', async (e) => {
    e.preventDefault();
    
    const submitBtn = form.querySelector('button[type="submit"]');
    submitBtn.classList.add('loading');
    
    try {
        // Collect form data
        const formData = new FormData(form);
        const data = Object.fromEntries(formData.entries());
        
        // Get export format
        data.exportFormat = form.querySelector('input[name="exportFormat"]:checked').value;
        
        console.log('Form data:', data);
        
        // Generate file based on format
        if (data.exportFormat === 'pdf') {
            await generatePDF(data);
        } else if (data.exportFormat === 'docx') {
            await generateDOCX(data);
        }
        
        showToast('Xuất file thành công!', 'success');
    } catch (error) {
        console.error('Error:', error);
        showToast('Có lỗi xảy ra: ' + error.message, 'error');
    } finally {
        submitBtn.classList.remove('loading');
    }
});

// Reset Form
function resetForm() {
    form.reset();
    showToast('Đã nhập lại form', 'success');
}

// Generate PDF
async function generatePDF(data) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Colors
    const primaryColor = [99, 102, 241];
    const textColor = [30, 41, 59];
    const mutedColor = [100, 116, 139];
    
    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('MẪU BIỂU HỘ KINH DOANH', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Thông tin Hộ kinh doanh', 105, 30, { align: 'center' });
    
    let y = 55;
    
    // Section 1: Business Info
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('I. THÔNG TIN HỘ KINH DOANH', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const businessFields = [
        ['Tên Hộ kinh doanh:', data.businessName || 'N/A'],
        ['Số giấy phép ĐKKD:', data.businessLicense || 'N/A'],
        ['Ngày cấp ĐKKD:', data.businessIssueDate || 'N/A'],
        ['Nơi cấp ĐKKD:', data.businessIssuePlace || 'N/A']
    ];
    
    businessFields.forEach(([label, value]) => {
        doc.setTextColor(...mutedColor);
        doc.text(label, 25, y);
        doc.setTextColor(...textColor);
        doc.text(value, 80, y);
        y += 8;
    });
    
    y += 10;
    
    // Section 2: Owner Info
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('II. THÔNG TIN CHỦ HỘ', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const ownerFields = [
        ['Tên chủ hộ:', data.ownerName || 'N/A'],
        ['Số CCCD:', data.ownerIdNumber || 'N/A'],
        ['Ngày cấp CCCD:', data.ownerIssueDate || 'N/A'],
        ['Nơi cấp CCCD:', data.ownerIssuePlace || 'N/A'],
        ['Ngày hết hạn CCCD:', data.ownerExpiryDate || 'N/A'],
        ['Địa chỉ:', data.businessAddress || 'N/A']
    ];
    
    ownerFields.forEach(([label, value]) => {
        doc.setTextColor(...mutedColor);
        doc.text(label, 25, y);
        doc.setTextColor(...textColor);
        doc.text(value, 80, y);
        y += 8;
    });
    
    // Footer
    doc.setTextColor(...mutedColor);
    doc.setFontSize(9);
    doc.text(`Ngày xuất: ${new Date().toLocaleDateString('vi-VN')}`, 20, 285);
    doc.text('Generated by Form', 105, 285, { align: 'center' });
    
    // Save
    doc.save(`mau_bieu_ho_kinh_doanh_${Date.now()}.pdf`);
}

// Generate DOCX
async function generateDOCX(data) {
    if (typeof window.docx === 'undefined') {
        throw new Error('Thư viện docx chưa được tải. Vui lòng tải lại trang.');
    }
    
    const Document = window.docx.Document;
    const Packer = window.docx.Packer;
    const Paragraph = window.docx.Paragraph;
    const TextRun = window.docx.TextRun;
    const HeadingLevel = window.docx.HeadingLevel;
    const AlignmentType = window.docx.AlignmentType;
    const Table = window.docx.Table;
    const TableRow = window.docx.TableRow;
    const TableCell = window.docx.TableCell;
    const WidthType = window.docx.WidthType;
    
    if (!Document || !Packer || !Paragraph || !TextRun) {
        throw new Error('Thư viện docx chưa được tải đầy đủ. Vui lòng tải lại trang.');
    }
    
    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                new Paragraph({
                    text: 'MẪU BIỂU HỘ KINH DOANH',
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 200 }
                }),
                
                new Paragraph({
                    text: 'Thông tin Hộ kinh doanh',
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 }
                }),
                
                new Paragraph({
                    text: 'I. THÔNG TIN HỘ KINH DOANH',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { before: 400, after: 200 }
                }),
                
                createTable([
                    ['Tên Hộ kinh doanh:', data.businessName || 'N/A'],
                    ['Số giấy phép ĐKKD:', data.businessLicense || 'N/A'],
                    ['Ngày cấp ĐKKD:', data.businessIssueDate || 'N/A'],
                    ['Nơi cấp ĐKKD:', data.businessIssuePlace || 'N/A']
                ]),
                
                new Paragraph({
                    text: 'II. THÔNG TIN CHỦ HỘ',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { before: 400, after: 200 }
                }),
                
                createTable([
                    ['Tên chủ hộ:', data.ownerName || 'N/A'],
                    ['Số CCCD:', data.ownerIdNumber || 'N/A'],
                    ['Ngày cấp CCCD:', data.ownerIssueDate || 'N/A'],
                    ['Nơi cấp CCCD:', data.ownerIssuePlace || 'N/A'],
                    ['Ngày hết hạn CCCD:', data.ownerExpiryDate || 'N/A'],
                    ['Địa chỉ:', data.businessAddress || 'N/A']
                ]),
                
                new Paragraph({
                    children: [
                        new TextRun({ 
                            text: `Ngày xuất: ${new Date().toLocaleDateString('vi-VN')}`,
                            size: 20,
                            color: '666666'
                        })
                    ],
                    spacing: { before: 400 }
                })
            ]
        }]
    });
    
    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mau_bieu_ho_kinh_doanh_${Date.now()}.docx`;
    a.click();
    URL.revokeObjectURL(url);
}

function createTable(rows) {
    const Table = window.docx.Table;
    const TableRow = window.docx.TableRow;
    const TableCell = window.docx.TableCell;
    const Paragraph = window.docx.Paragraph;
    const TextRun = window.docx.TextRun;
    const WidthType = window.docx.WidthType;
    
    return new Table({
        rows: rows.map(([label, value]) => 
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph({
                            children: [new TextRun({ text: label, bold: true })]
                        })],
                        shading: { fill: 'F8FAFC' }
                    }),
                    new TableCell({
                        children: [new Paragraph(value || 'N/A')]
                    })
                ]
            })
        ),
        width: { size: 100, type: WidthType.PERCENTAGE }
    });
}

function showToast(message, type = 'success') {
    const existingToast = document.querySelector('.toast');
    if (existingToast) {
        existingToast.remove();
    }
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `
        ${type === 'success' 
            ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>'
            : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>'
        }
        <span>${message}</span>
    `;
    
    document.body.appendChild(toast);
    
    setTimeout(() => {
        toast.classList.add('show');
    }, 10);
    
    setTimeout(() => {
        toast.classList.remove('show');
        setTimeout(() => toast.remove(), 300);
    }, 3000);
}

window.resetForm = resetForm;
window.generatePDF = generatePDF;
window.generateDOCX = generateDOCX;